/**
 * Standardized Error Codes for AgentPay API
 * 
 * Format: CATEGORY_SPECIFIC_ERROR
 * Categories:
 * - AUTH: Authentication/Authorization errors
 * - AGENT: Agent-related errors
 * - PAYMENT: Payment/transaction errors
 * - BUDGET: Budget/spending limit errors
 * - METER: Usage metering errors
 * - VALIDATION: Request validation errors
 * - RATE_LIMIT: Rate limiting errors
 * - INTERNAL: Internal server errors
 */

export const ErrorCodes = {
  // ==================== Authentication & Authorization ====================
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INVALID_API_KEY: "AUTH_INVALID_API_KEY",
  AUTH_API_KEY_NOT_CONFIGURED: "AUTH_API_KEY_NOT_CONFIGURED",
  AUTH_MISSING_HEADER: "AUTH_MISSING_HEADER",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_INSUFFICIENT_PERMISSIONS: "AUTH_INSUFFICIENT_PERMISSIONS",

  // ==================== Agent Errors ====================
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  AGENT_ALREADY_EXISTS: "AGENT_ALREADY_EXISTS",
  AGENT_REGISTRATION_FAILED: "AGENT_REGISTRATION_FAILED",
  AGENT_UPDATE_FAILED: "AGENT_UPDATE_FAILED",
  AGENT_SUSPENDED: "AGENT_SUSPENDED",
  AGENT_INVALID_STATE: "AGENT_INVALID_STATE",

  // ==================== Payment Errors ====================
  PAYMENT_INSUFFICIENT_FUNDS: "PAYMENT_INSUFFICIENT_FUNDS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_INVALID_AMOUNT: "PAYMENT_INVALID_AMOUNT",
  PAYMENT_RECIPIENT_NOT_FOUND: "PAYMENT_RECIPIENT_NOT_FOUND",
  PAYMENT_ALREADY_PROCESSED: "PAYMENT_ALREADY_PROCESSED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  PAYMENT_PAYER_NOT_CONFIGURED: "PAYMENT_PAYER_NOT_CONFIGURED",
  PAYMENT_TOPUP_FAILED: "PAYMENT_TOPUP_FAILED",
  PAYMENT_SETTLEMENT_FAILED: "PAYMENT_SETTLEMENT_FAILED",

  // ==================== Budget & Spending Errors ====================
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  BUDGET_DAILY_LIMIT_EXCEEDED: "BUDGET_DAILY_LIMIT_EXCEEDED",
  BUDGET_PER_CALL_LIMIT_EXCEEDED: "BUDGET_PER_CALL_LIMIT_EXCEEDED",
  BUDGET_SPENDING_PAUSED: "BUDGET_SPENDING_PAUSED",
  BUDGET_AUTHORIZATION_FAILED: "BUDGET_AUTHORIZATION_FAILED",
  BUDGET_RESERVATION_EXPIRED: "BUDGET_RESERVATION_EXPIRED",
  BUDGET_RESERVATION_NOT_FOUND: "BUDGET_RESERVATION_NOT_FOUND",

  // ==================== Metering Errors ====================
  METER_LOG_FAILED: "METER_LOG_FAILED",
  METER_INVALID_TOKENS: "METER_INVALID_TOKENS",
  METER_TOOL_NOT_FOUND: "METER_TOOL_NOT_FOUND",

  // ==================== Pricing Errors ====================
  PRICING_QUOTE_EXPIRED: "PRICING_QUOTE_EXPIRED",
  PRICING_QUOTE_NOT_FOUND: "PRICING_QUOTE_NOT_FOUND",
  PRICING_CALCULATION_FAILED: "PRICING_CALCULATION_FAILED",
  PRICING_INVALID_RATE: "PRICING_INVALID_RATE",
  PRICING_FREEZE_ACTIVE: "PRICING_FREEZE_ACTIVE",

  // ==================== Pre-Authorization Errors ====================
  PREAUTH_RESERVATION_FAILED: "PREAUTH_RESERVATION_FAILED",
  PREAUTH_CAPTURE_FAILED: "PREAUTH_CAPTURE_FAILED",
  PREAUTH_RELEASE_FAILED: "PREAUTH_RELEASE_FAILED",
  PREAUTH_ALREADY_CAPTURED: "PREAUTH_ALREADY_CAPTURED",
  PREAUTH_ALREADY_RELEASED: "PREAUTH_ALREADY_RELEASED",

  // ==================== Validation Errors ====================
  VALIDATION_REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
  VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",
  VALIDATION_INVALID_TYPE: "VALIDATION_INVALID_TYPE",
  VALIDATION_OUT_OF_RANGE: "VALIDATION_OUT_OF_RANGE",
  VALIDATION_CONSTRAINT_VIOLATION: "VALIDATION_CONSTRAINT_VIOLATION",

  // ==================== Rate Limiting ====================
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  RATE_LIMIT_QUOTA_EXHAUSTED: "RATE_LIMIT_QUOTA_EXHAUSTED",

  // ==================== Messaging Errors ====================
  MESSAGE_SEND_FAILED: "MESSAGE_SEND_FAILED",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  MESSAGE_INVALID_RECIPIENT: "MESSAGE_INVALID_RECIPIENT",

  // ==================== Webhook Errors ====================
  WEBHOOK_DELIVERY_FAILED: "WEBHOOK_DELIVERY_FAILED",
  WEBHOOK_INVALID_URL: "WEBHOOK_INVALID_URL",
  WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND",

  // ==================== x402 Protocol Errors ====================
  X402_PAYMENT_REQUIRED: "X402_PAYMENT_REQUIRED",
  X402_INVALID_SIGNATURE: "X402_INVALID_SIGNATURE",
  X402_NONCE_EXPIRED: "X402_NONCE_EXPIRED",
  X402_NONCE_ALREADY_USED: "X402_NONCE_ALREADY_USED",

  // ==================== Internal Errors ====================
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INTERNAL_DATABASE_ERROR: "INTERNAL_DATABASE_ERROR",
  INTERNAL_NETWORK_ERROR: "INTERNAL_NETWORK_ERROR",
  INTERNAL_SERVICE_UNAVAILABLE: "INTERNAL_SERVICE_UNAVAILABLE",
  INTERNAL_CONFIGURATION_ERROR: "INTERNAL_CONFIGURATION_ERROR",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

/**
 * HTTP status code mapping for error codes
 */
export const ErrorHttpStatus: Record<ErrorCode, number> = {
  // Auth - 401/403
  AUTH_UNAUTHORIZED: 401,
  AUTH_INVALID_API_KEY: 401,
  AUTH_API_KEY_NOT_CONFIGURED: 500,
  AUTH_MISSING_HEADER: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_INSUFFICIENT_PERMISSIONS: 403,

  // Agent - 400/404/409
  AGENT_NOT_FOUND: 404,
  AGENT_ALREADY_EXISTS: 409,
  AGENT_REGISTRATION_FAILED: 500,
  AGENT_UPDATE_FAILED: 500,
  AGENT_SUSPENDED: 403,
  AGENT_INVALID_STATE: 400,

  // Payment - 400/402/500
  PAYMENT_INSUFFICIENT_FUNDS: 402,
  PAYMENT_FAILED: 500,
  PAYMENT_INVALID_AMOUNT: 400,
  PAYMENT_RECIPIENT_NOT_FOUND: 404,
  PAYMENT_ALREADY_PROCESSED: 409,
  PAYMENT_REQUIRED: 402,
  PAYMENT_VERIFICATION_FAILED: 400,
  PAYMENT_PAYER_NOT_CONFIGURED: 500,
  PAYMENT_TOPUP_FAILED: 500,
  PAYMENT_SETTLEMENT_FAILED: 500,

  // Budget - 400/402/403
  BUDGET_EXCEEDED: 402,
  BUDGET_DAILY_LIMIT_EXCEEDED: 402,
  BUDGET_PER_CALL_LIMIT_EXCEEDED: 402,
  BUDGET_SPENDING_PAUSED: 403,
  BUDGET_AUTHORIZATION_FAILED: 402,
  BUDGET_RESERVATION_EXPIRED: 410,
  BUDGET_RESERVATION_NOT_FOUND: 404,

  // Metering - 400/500
  METER_LOG_FAILED: 500,
  METER_INVALID_TOKENS: 400,
  METER_TOOL_NOT_FOUND: 404,

  // Pricing - 400/404/410
  PRICING_QUOTE_EXPIRED: 410,
  PRICING_QUOTE_NOT_FOUND: 404,
  PRICING_CALCULATION_FAILED: 500,
  PRICING_INVALID_RATE: 400,
  PRICING_FREEZE_ACTIVE: 409,

  // Pre-Auth - 400/404/409
  PREAUTH_RESERVATION_FAILED: 500,
  PREAUTH_CAPTURE_FAILED: 500,
  PREAUTH_RELEASE_FAILED: 500,
  PREAUTH_ALREADY_CAPTURED: 409,
  PREAUTH_ALREADY_RELEASED: 409,

  // Validation - 400
  VALIDATION_REQUIRED_FIELD: 400,
  VALIDATION_INVALID_FORMAT: 400,
  VALIDATION_INVALID_TYPE: 400,
  VALIDATION_OUT_OF_RANGE: 400,
  VALIDATION_CONSTRAINT_VIOLATION: 400,

  // Rate Limiting - 429
  RATE_LIMIT_EXCEEDED: 429,
  RATE_LIMIT_QUOTA_EXHAUSTED: 429,

  // Messaging - 400/404/500
  MESSAGE_SEND_FAILED: 500,
  MESSAGE_NOT_FOUND: 404,
  MESSAGE_INVALID_RECIPIENT: 400,

  // Webhook - 400/404/500
  WEBHOOK_DELIVERY_FAILED: 500,
  WEBHOOK_INVALID_URL: 400,
  WEBHOOK_NOT_FOUND: 404,

  // x402 - 400/402
  X402_PAYMENT_REQUIRED: 402,
  X402_INVALID_SIGNATURE: 400,
  X402_NONCE_EXPIRED: 410,
  X402_NONCE_ALREADY_USED: 409,

  // Internal - 500/503
  INTERNAL_ERROR: 500,
  INTERNAL_DATABASE_ERROR: 500,
  INTERNAL_NETWORK_ERROR: 502,
  INTERNAL_SERVICE_UNAVAILABLE: 503,
  INTERNAL_CONFIGURATION_ERROR: 500,
};

/**
 * Default error messages for each error code
 */
export const ErrorMessages: Record<ErrorCode, string> = {
  // Auth
  AUTH_UNAUTHORIZED: "Authentication required",
  AUTH_INVALID_API_KEY: "Invalid API key",
  AUTH_API_KEY_NOT_CONFIGURED: "API key not configured on server",
  AUTH_MISSING_HEADER: "Missing required authentication header",
  AUTH_TOKEN_EXPIRED: "Authentication token has expired",
  AUTH_INSUFFICIENT_PERMISSIONS: "Insufficient permissions for this action",

  // Agent
  AGENT_NOT_FOUND: "Agent not found",
  AGENT_ALREADY_EXISTS: "Agent with this ID already exists",
  AGENT_REGISTRATION_FAILED: "Failed to register agent",
  AGENT_UPDATE_FAILED: "Failed to update agent",
  AGENT_SUSPENDED: "Agent account is suspended",
  AGENT_INVALID_STATE: "Agent is in an invalid state for this operation",

  // Payment
  PAYMENT_INSUFFICIENT_FUNDS: "Insufficient funds for this transaction",
  PAYMENT_FAILED: "Payment transaction failed",
  PAYMENT_INVALID_AMOUNT: "Invalid payment amount",
  PAYMENT_RECIPIENT_NOT_FOUND: "Payment recipient not found",
  PAYMENT_ALREADY_PROCESSED: "Payment has already been processed",
  PAYMENT_REQUIRED: "Payment required to proceed",
  PAYMENT_VERIFICATION_FAILED: "Payment verification failed",
  PAYMENT_PAYER_NOT_CONFIGURED: "Solana payer not configured",
  PAYMENT_TOPUP_FAILED: "Balance top-up failed",
  PAYMENT_SETTLEMENT_FAILED: "Settlement transaction failed",

  // Budget
  BUDGET_EXCEEDED: "Budget limit exceeded",
  BUDGET_DAILY_LIMIT_EXCEEDED: "Daily spending limit exceeded",
  BUDGET_PER_CALL_LIMIT_EXCEEDED: "Per-call cost limit exceeded",
  BUDGET_SPENDING_PAUSED: "Spending is paused for this agent",
  BUDGET_AUTHORIZATION_FAILED: "Budget authorization failed",
  BUDGET_RESERVATION_EXPIRED: "Budget reservation has expired",
  BUDGET_RESERVATION_NOT_FOUND: "Budget reservation not found",

  // Metering
  METER_LOG_FAILED: "Failed to log usage",
  METER_INVALID_TOKENS: "Invalid token count",
  METER_TOOL_NOT_FOUND: "Tool not found",

  // Pricing
  PRICING_QUOTE_EXPIRED: "Price quote has expired",
  PRICING_QUOTE_NOT_FOUND: "Price quote not found",
  PRICING_CALCULATION_FAILED: "Failed to calculate price",
  PRICING_INVALID_RATE: "Invalid pricing rate",
  PRICING_FREEZE_ACTIVE: "Price freeze is currently active",

  // Pre-Auth
  PREAUTH_RESERVATION_FAILED: "Failed to create reservation",
  PREAUTH_CAPTURE_FAILED: "Failed to capture reservation",
  PREAUTH_RELEASE_FAILED: "Failed to release reservation",
  PREAUTH_ALREADY_CAPTURED: "Reservation has already been captured",
  PREAUTH_ALREADY_RELEASED: "Reservation has already been released",

  // Validation
  VALIDATION_REQUIRED_FIELD: "Required field is missing",
  VALIDATION_INVALID_FORMAT: "Invalid format",
  VALIDATION_INVALID_TYPE: "Invalid type",
  VALIDATION_OUT_OF_RANGE: "Value is out of allowed range",
  VALIDATION_CONSTRAINT_VIOLATION: "Constraint violation",

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "Rate limit exceeded",
  RATE_LIMIT_QUOTA_EXHAUSTED: "API quota exhausted",

  // Messaging
  MESSAGE_SEND_FAILED: "Failed to send message",
  MESSAGE_NOT_FOUND: "Message not found",
  MESSAGE_INVALID_RECIPIENT: "Invalid message recipient",

  // Webhook
  WEBHOOK_DELIVERY_FAILED: "Webhook delivery failed",
  WEBHOOK_INVALID_URL: "Invalid webhook URL",
  WEBHOOK_NOT_FOUND: "Webhook not found",

  // x402
  X402_PAYMENT_REQUIRED: "Payment required (x402)",
  X402_INVALID_SIGNATURE: "Invalid payment signature",
  X402_NONCE_EXPIRED: "Payment nonce has expired",
  X402_NONCE_ALREADY_USED: "Payment nonce has already been used",

  // Internal
  INTERNAL_ERROR: "Internal server error",
  INTERNAL_DATABASE_ERROR: "Database error",
  INTERNAL_NETWORK_ERROR: "Network error",
  INTERNAL_SERVICE_UNAVAILABLE: "Service temporarily unavailable",
  INTERNAL_CONFIGURATION_ERROR: "Server configuration error",
};
