/**
 * Monocle x402 Devnet Wallet Setup
 *
 * Generates a Solana devnet wallet for x402 payments and prints
 * the .env configuration you need to paste.
 *
 * Usage:
 *   cd agent-backend
 *   npx ts-node scripts/setup-x402-wallet.ts
 *
 * After running:
 * 1. Copy the .env lines into your .env file
 * 2. Go to https://faucet.solana.com — airdrop 2 SOL to the public key
 * 3. Go to https://faucet.circle.com — get devnet USDC to the public key
 * 4. Restart the backend
 */

import { Keypair } from "@solana/web3.js";
import * as fs from "fs";
import * as path from "path";

function main() {
  console.log("\n🔑 Generating Solana devnet wallet for x402...\n");

  const kp = Keypair.generate();
  const publicKey = kp.publicKey.toBase58();
  const secretKeyArray = JSON.stringify(Array.from(kp.secretKey));

  console.log("═══════════════════════════════════════════════════");
  console.log("  Public Key:  ", publicKey);
  console.log("═══════════════════════════════════════════════════");
  console.log();

  const envBlock = [
    "",
    "# =============================================================================",
    "# x402 PAYMENT PROTOCOL (Generated by setup-x402-wallet.ts)",
    "# =============================================================================",
    "SOLANA_NETWORK=devnet",
    `X402_PAY_TO=${publicKey}`,
    `X402_CLIENT_PRIVATE_KEY=${secretKeyArray}`,
    "X402_FACILITATOR_URL=https://x402.org/facilitator",
    "X402_CHAT_PRICE=0.001",
  ].join("\n");

  console.log("Add these lines to your .env:\n");
  console.log(envBlock);
  console.log();

  // Optionally append to .env
  const envPath = path.join(__dirname, "..", ".env");
  if (fs.existsSync(envPath)) {
    const existing = fs.readFileSync(envPath, "utf-8");

    if (existing.includes("X402_PAY_TO=") && !existing.includes("X402_PAY_TO=\n") && !existing.includes("X402_PAY_TO=\r\n")) {
      console.log("⚠️  .env already has X402_PAY_TO set. Not overwriting.");
      console.log("   To replace, remove the existing x402 vars first.\n");
    } else {
      // Remove empty X402_PAY_TO= lines and append
      let cleaned = existing
        .replace(/\nX402_PAY_TO=\s*$/m, "")
        .replace(/\nX402_CLIENT_PRIVATE_KEY=\s*$/m, "");
      fs.writeFileSync(envPath, cleaned.trimEnd() + "\n" + envBlock + "\n");
      console.log("✅ Appended to .env\n");
    }
  } else {
    console.log("⚠️  No .env file found. Create one from env.sample first.\n");
  }

  console.log("Next steps:");
  console.log("  1. Airdrop devnet SOL:  https://faucet.solana.com");
  console.log(`     → Paste: ${publicKey}`);
  console.log("  2. Get devnet USDC:     https://faucet.circle.com");
  console.log(`     → Select Solana devnet, paste: ${publicKey}`);
  console.log("  3. Restart the backend: npm run dev");
  console.log();
}

main();
